## 函数

### 声明

函数声明包括函数名、形参列表、返回值列表（可省略）以及函数体。

```go
func sum(x, y int) int {
  return x + y
}
```

在声明可变参数函数时，需要在参数列表的最后一个参数类型之前加上省略符号 `...`，这表示该函数会接收任意数量的该类型参数。

在函数体中，`vals` 被看作是类型为 `[]int` 的切片。

```go
func sum(vals ...int) (total int) {
  for _, val := range vals {
    total += val
  }
  return
}
```

### 调用

每一次函数调用都必须按照声明顺序为所有参数提供实参（参数值）。

```go
func sigma(x int) int {
  if x <= 0 {
    return 0
  }
  return sigma(x-1) + x
}
```

### panic

Go 的类型系统会在编译时捕获很多错误，但有些错误只能在运行时检查，如数组访问越界、空指针引用等。这些运行时错误会引起 panic 异常。

一般而言，当 panic 异常发生时，程序会中断运行，并输出日志信息。

```
panic: runtime error: index out of range [3] with length 2

goroutine 1 [running]:
main.main()
        /gardener/golang/sample/main.go:11 +0x1d
exit status 2
```

### defer

```go
func TestDefer(t *testing.T) {
  var f, err = os.Open(name)
  defer f.Close()
  ...
}
```

当 defer 语句被执行时，跟在 defer 后面的函数会被延迟执行。直到包含该 defer 语句的函数执行完毕时，defer 后的函数才会被执行，不论包含 defer 语句的函数是通过 return 正常结束，还是由于 panic 导致的异常结束。

### recover

通常来说，不应该对 panic 异常做任何处理，但有时，我们可以从异常中恢复，在程序崩溃前，做一些操作。当 web 服务器发生 panic 时，在崩溃前应该将所有的连接关闭。

```go
func TestRecover(t *testing.T) {
  defer func() {
    if r := recover(); r != nil {
      log.Println(r)
    }
  }()
  panic("don't panic")
}
```

不管三七二十一恢复所有的 panic 不是可取的做法；因为在 panic 之后，无法保证全局变量的状态仍然和我们预期一致。

作为被广泛遵守的规范，不应该试图去恢复其他包引起的 panic 。公有的 API 应该将函数的运行失败作为 error 返回，而不是 panic。



### 课后作业

使用 panic 和 recover 编写一个不包含 return 语句但能返回一个非零值的函数。

### 拓展知识 
> Go 支持匿名函数， 并能用其构造 闭包。 匿名函数在你想定义一个不需要命名的内联函数时是很实用的

```go
package main

import "fmt"

func intSeq() func() int {
    i := 0
    return func() int {
        i++
        return i
    }
}

func main() {

    nextInt := intSeq()

    fmt.Println(nextInt())
    fmt.Println(nextInt())
    fmt.Println(nextInt())

    newInts := intSeq()
    fmt.Println(newInts())
}
```
